### ISSUE TITLE
(index):1 Uncaught SyntaxError: Unexpected token ( 08:10:52.316 (index):1 Uncaught SyntaxError: Unexpected token ( 08:10:52.353 (index):1 Uncaught SyntaxError: Unexpected token (

### ISSUE THREAD

**Issue by joshuairl** [raphamorim/react-tv#121] opened 2018-04-30 12:14 UTC
So I'm getting these hard to track down errors when working with `video`.
Wondering if there is a way you guys have found to find the issue or track it down?
Can't find a place to put a breakpoint really so not sure how to approach it.

`Uncaught SyntaxError: Unexpected token ( (index):1`

![image](https://user-images.githubusercontent.com/171077/39426572-60228992-4c4e-11e8-9c79-5443f554ef00.png)

When switching to `react-dom` it seems to work okay.  Guessing its something specific to the limitations of the renderer but I'm not quite sure where to debug it.

**Comment by raphamorim** [comment] 2018-04-30 13:34
Hi @joshuairl, Can you share with me the code for it and the webpack config?
I'll try to reproduce it locally.

**Comment by joshuairl** [comment] 2018-04-30 13:41
Gah… I found the problem!
Was a plugin that was using like umm somehow `<video oncanplay=function ( ) { } />`.

Hmm It didn’t like that syntax in development it failed, but in production it worked.  Guessing its doing something specific for development.

**Comment by raphamorim** [comment] 2018-04-30 13:45
Maybe worked only because Webpack with PROD environment tries to uglify and sometimes change the reference of functions/variables and fixed that automatically. I don't know exactly why. It's just a guess.

So I will close this issue 👍 
thx

**Closed by raphamorim** 2018-04-30 13:45 UTC

**Comment by joshuairl** [comment] 2018-04-30 13:48
```
render() {
    const { vendor, src, extraProps } = this.props

    return createElement(vendor, {
      ref: c => (this._player = c),
      src,
      ...extraProps,
      ...this._playerEvents,
    })
  }
```
